CREATE TABLE IF NOT EXISTS `PREFIX_collectlogs_js_error` (
    `id_collectlogs_js_error` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `id_shop`               INT(11) UNSIGNED NOT NULL DEFAULT 1,
    `id_lang`               INT(11) UNSIGNED NULL,
    `id_customer`           INT(11) UNSIGNED NULL,
    `guest_token`           VARCHAR(64) NULL,
    `severity`              ENUM('info','warn','error','fatal') NOT NULL DEFAULT 'error',
    `message`               VARCHAR(1000) NOT NULL DEFAULT '',
    `error_type`            VARCHAR(128) NOT NULL DEFAULT '',
    `url`                   TEXT NOT NULL,
    `referrer`              TEXT NULL,
    `user_agent`            TEXT NOT NULL,
    `dt_iso`                DATETIME NOT NULL,
    `stack_trace_json`      LONGTEXT NULL,
    `extra_json`            LONGTEXT NULL,
    `script_url`            TEXT NULL,
    `line`                  INT(11) UNSIGNED NULL,
    `col`                   INT(11) UNSIGNED NULL,
    `fingerprint`           CHAR(40) NOT NULL DEFAULT '',
    `occurrences`           INT(11) UNSIGNED NOT NULL DEFAULT 1,
    `first_seen`            DATETIME NOT NULL,
    `last_seen`             DATETIME NOT NULL,
    PRIMARY KEY (`id_collectlogs_js_error`),
    KEY `fingerprint_shop` (`fingerprint`, `id_shop`),
    KEY `last_seen` (`last_seen`),
    KEY `id_shop` (`id_shop`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=CHARSET_TYPE COLLATE=COLLATE_TYPE;
